POST http://localhost:3003/user/create 
Content-Type: application/json

{
"name":"Jao", "email": "jao@gmail.com", "password": "654321"
}

### 
POST http://localhost:3003/post/create 
Content-Type: application/json

{
"photo":"Foto do cachorro", "description": "Gato com lingua pra fora", "type": "normal", "authorId": "59d42260-37a1-4f05-b20a-da5674f58c77"
}

### 
GET http://localhost:3003/post/getId/dcd74e21-a110-4038-8f28-6525f2d0bbb8
Content-Type: application/json

### 
POST http://localhost:3003/user/makeFriendship 
Content-Type: application/json

{
"idUser":"59d42260-37a1-4f05-b20a-da5674f58c77", "idFriend":"3f89e2d0-763b-4e89-9f50-bf718d1c6158"
}

### 
DELETE http://localhost:3003/user/endFriendship 
Content-Type: application/json

{
"idUser":"59d42260-37a1-4f05-b20a-da5674f58c77", "idFriend":"3f89e2d0-763b-4e89-9f50-bf718d1c6158"
}

### 
GET http://localhost:3003/post/seeFeed 
Content-Type: application/json